#!/usr/bin/env bash
#
# Usage:  slack-post [ -h | --help | -v | --version ]
#         slack-post [options]
#
# Description:
#   Simple notifier for Slack.
#
# Options:
#   -h, --help          Print usage
#   -v, --version       Print version information and quit
#   --channel           Slack channel name [default: $SLACK_CHANNEL]
#   --user              Slack user name [default: $SLACK_USER]
#   --icon-url          Slack icon URL [default: $SLACK_ICON_URL]
#   --icon-emoji        Slack icon emoji [default: $SLACK_ICON_EMOJI]
#   --url               Slack webhook URL [default: $SLACK_URL]
#   --proxy             Proxy URL [default: $HTTPS_PROXY]
#   --text              Message text to notify
#
# Example:
#   $ slack-post \
#       --channel random \
#       --user notifier \
#       --url https://hooks.slack.com/services/xxxxxxxxx/yyyyyyyyy/zzzzzzzzzzzzzzzzzzzzzzzz \
#       --text 'Test notification'

set -e

[[ "${1}" = '--debug' ]] \
  && set -x \
  && shift 1

SCRIPT_NAME='slack-post'
SCRIPT_VERSION='0.1.0'
SCRIPT_PATH="$(dirname ${0})/$(basename ${0})"

CHANNEL="${SLACK_CHANNEL}"
USER="${SLACK_USER}"
ICON_URL="${SLACK_ICON_URL}"
ICON_EMOJI="${SLACK_ICON_EMOJI}"
URL="${SLACK_URL}"
PROXY="${HTTPS_PROXY}"
TEXT=''

function print_version {
  echo "${SCRIPT_NAME}: ${SCRIPT_VERSION}"
}

function print_usage {
  sed -ne '1,2d; /^#/!q; s/^#$/# /; s/^# //p;' ${SCRIPT_PATH}
}

function abort {
  echo "${SCRIPT_NAME}: ${*}" >&2
  exit 1
}

while [[ -n "${1}" ]]; do
  case "${1}" in
    '-v' | '--version' )
      print_version && exit 0
      ;;
    '-h' | '--help' )
      print_usage && exit 0
      ;;
    '--channel' )
      CHANNEL="${2}" && shift 2
      ;;
    '--user' )
      USER="${2}" && shift 2
      ;;
    '--icon-url' )
      ICON_URL="${2}" && shift 2
      ;;
    '--icon-emoji' )
      ICON_EMOJI="${2}" && shift 2
      ;;
    '--url' )
      URL="${2}" && shift 2
      ;;
    '--proxy' )
      PROXY="${2}" && shift 2
      ;;
    '--text' )
      TEXT="${2}" && shift 2
      ;;
    * )
      abort "invalid argument \`${1}\`"
      ;;
  esac
done

set -u

[[ -n "${CHANNEL}" ]] || abort 'missing channel name'
[[ -n "${USER}" ]] || abort 'missing user name'
[[ -n "${URL}" ]] || abort 'missing web hook url'
[[ -n "${TEXT}" ]] || abort 'missing message text'

[[ -n "${PROXY}" ]] \
  && OPT_PROXY="--proxy ${PROXY}" \
  && OPT_PROXY=''

PAYLOAD=(
  "'channel': '#${CHANNEL}',"
  "'username': '${USER}',"
  "'icon_url': '${ICON_URL}',"
  "'icon_emoji': '${ICON_EMOJI}',"
  "'text': '${TEXT}'"
)

curl -sSX POST --data-urlencode "payload={${PAYLOAD[*]}}" ${OPT_PROXY} ${URL}
